
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Beakal.A
 */
public class pricecalc extends javax.swing.JFrame {

    /**
     * Creates new form pricecalc
     */
    double book = 10;
    double chart = 20;
    double paint = 30;
    double stickers = 40;
    //double r;
    double tax = 15;
    
    
    
    public pricecalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setText("AB STATIONARY PRICE CALCULATOR");

        jLabel8.setFont(new java.awt.Font("Century", 3, 18)); // NOI18N
        jLabel8.setText("Total cost of items");

        jCheckBox1.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jCheckBox1.setText("TAX/VAT");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel12.setText("Total Amount");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jTextField12)
                    .addComponent(jTextField5))
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel3.setText("Amount");

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setText("Items");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jCheckBox3.setText("Books");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jCheckBox4.setText("Charts");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jCheckBox5.setText("Paints");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jCheckBox6.setText("Stickers");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(112, 112, 112))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTextField1.setText("");  
jTextField2.setText(""); 
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText(""); 
jTextField11.setText(""); 
jTextField12.setText("");
jCheckBox1.setSelected(false);
jCheckBox3.setSelected(false);
jCheckBox4.setSelected(false);
jCheckBox5.setSelected(false);
jCheckBox6.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


double B, C, P, S,x, r, total;
if(jCheckBox3.isSelected()){
double b = Double.parseDouble(jTextField1.getText());
B = (b * book);
r = B;
String rb = String.format("%.2f", B); 
jTextField12.setText(rb);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(rb);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox4.isSelected()){
    double c = Double.parseDouble(jTextField2.getText());
C = (c * chart);
r = C;
String rc = String.format("%.2f", C); 
jTextField12.setText(rc);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(rc);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox5.isSelected()){
    double p = Double.parseDouble(jTextField3.getText());
P = (p * paint);
r = P;
String rp = String.format("%.2f", P); 
jTextField12.setText(rp);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(rp);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox6.isSelected()){
     double s = Double.parseDouble(jTextField4.getText());
S = (s * stickers);
r = S;
String rs = String.format("%.2f", S); 
jTextField12.setText(rs);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(rs);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox3.isSelected() && jCheckBox4.isSelected()){
    double b = Double.parseDouble(jTextField1.getText());
    double c = Double.parseDouble(jTextField2.getText());
B = (b * book);
C = (c * chart);
r = (b * book) + (c * chart);
String bc = String.format("%.2f", r); 
jTextField12.setText(bc);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(bc);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox3.isSelected() && jCheckBox5.isSelected()){
    double p = Double.parseDouble(jTextField3.getText());
    double b = Double.parseDouble(jTextField1.getText());
B = (b * book);
P = (p * paint);
r = (b * book) + (p * paint);
String bp = String.format("%.2f", r); 
jTextField12.setText(bp);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(bp);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox3.isSelected() && jCheckBox6.isSelected()){
    double b = Double.parseDouble(jTextField1.getText());
    double s = Double.parseDouble(jTextField4.getText());
B = (b * book);
S = (s * stickers);
r = (b * book) + (s * stickers);
String bs = String.format("%.2f", r); 
jTextField12.setText(bs);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(bs);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox4.isSelected() && jCheckBox5.isSelected()){
    double c = Double.parseDouble(jTextField2.getText());
    double p = Double.parseDouble(jTextField3.getText());
C = (c * chart);
P = (p * paint);
r = (c * chart) + (p * paint);
String cp = String.format("%.2f", r); 
jTextField12.setText(cp);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(cp);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox4.isSelected() && jCheckBox6.isSelected()){
    double c = Double.parseDouble(jTextField2.getText());
    double s = Double.parseDouble(jTextField4.getText());
C = (c * chart);
S = (s * stickers);
r = (c * chart) +  (s * stickers);
String cs = String.format("%.2f", r); 
jTextField12.setText(cs);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(cs);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox5.isSelected() && jCheckBox6.isSelected()){
    double s = Double.parseDouble(jTextField4.getText());
    double p = Double.parseDouble(jTextField3.getText());
P = (p * paint);
S = (s * stickers);
r = (p * paint) +  (s * stickers);
String ps = String.format("%.2f", r); 
jTextField12.setText(ps);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(ps);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected()){
    double c = Double.parseDouble(jTextField2.getText());
    double p = Double.parseDouble(jTextField3.getText());
double s = Double.parseDouble(jTextField4.getText());
C = (c * chart);
P = (p * paint);
S = (s * stickers);
r = C + P + S;
String ps = String.format("%.2f", r); 
jTextField12.setText(ps);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(ps);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}

if(jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()){
    double b = Double.parseDouble(jTextField1.getText());
    double p = Double.parseDouble(jTextField3.getText());
    double c = Double.parseDouble(jTextField2.getText());

B = (b * book);
C = (c * chart);
P = (p * paint);

r = B + C + P;
String ps = String.format("%.2f", r); 
jTextField12.setText(ps);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(ps);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox3.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected()){
    double b = Double.parseDouble(jTextField1.getText());
    double s = Double.parseDouble(jTextField4.getText());
    double p = Double.parseDouble(jTextField3.getText());
B = (b * book);
P = (p * paint);
S = (s * stickers);
r = B + S + P;
String ps = String.format("%.2f", r); 
jTextField12.setText(ps);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(ps);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected()){
    double b = Double.parseDouble(jTextField1.getText());
    double c = Double.parseDouble(jTextField2.getText());
    double s = Double.parseDouble(jTextField4.getText());
    double p = Double.parseDouble(jTextField3.getText());
B = (b * book);
C = (c * chart);
P = (p * paint);
S = (s * stickers);
r= B + C + P + S;
String ps = String.format("%.2f", r); 
jTextField12.setText(ps);
if(!(jCheckBox1.isSelected())  ){
jTextField5.setText(ps);
}
if(jCheckBox1.isSelected()){
x = ((r * tax)/100);
total = (r + x);
String VATTAX = String.format("%.2f", x);
String TotalCost = String.format("%.2f", total);
jTextField5.setText(TotalCost);
jTextField11.setText(VATTAX);
}
}
if(!(jCheckBox3.isSelected()) && !(jCheckBox4.isSelected()) && !(jCheckBox5.isSelected()) && !(jCheckBox6.isSelected())){
 JOptionPane.showMessageDialog(null, "Please enter a value in the fields");
}
//if(jCheckBox1.isSelected()){
//double b = Double.parseDouble(jTextField1.getText());
//double c = Double.parseDouble(jTextField2.getText());
//double p = Double.parseDouble(jTextField3.getText());
//double s = Double.parseDouble(jTextField4.getText());
////double tax = Double.parseDouble(jTextField11.getText());
////double vat = Double.parseDouble(jTextField13.getText());
//B = (b * book);
//C = (c * chart);
//P = (p * paint);
//S = (s * stickers);
//r= B + C + P + S;
//String res = String.format("%.2f", r); 
//
//x = ((r * tax)/100);
//total = (r + x);
//String VATTAX = String.format("%.2f", x);
//String TotalCost = String.format("%.2f", total);
//jTextField5.setText(TotalCost);
//jTextField11.setText(VATTAX);
//}
//

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pricecalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pricecalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pricecalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pricecalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pricecalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
